---
title: "Cyano Recovery Test Summary"
author: "Laura Hmelo"
date: "7/31/2017"
output: html_document
---

```{r setup, include=FALSE}
library(plyr)
library(tidyverse)
```


set datapaths
```{r}
summarypath <- "~/Desktop/MetabolomicsProjects/SPEvsEtOAcTest/RecoveryTests"
datapath_pH5 <- "~/Desktop/MetabolomicsProjects/SPEvsEtOAcTest/RecoveryTests/Cyano_pH5"
datapath_pH2 <- "~/Desktop/MetabolomicsProjects/SPEvsEtOAcTest/RecoveryTests/Cyano_pH2"
datapath_pH8 <- "~/Desktop/MetabolomicsProjects/SPEvsEtOAcTest/RecoveryTests/Cyano_pH8"
```


Load in Recovery Data
```{r}
setwd(datapath_pH5)
recovery_pH5 <- read.csv("RecoveryValues_postBMIS_pH5_Cyano.csv", row.names = 1)

recovery_pH5 <- recovery_pH5 %>% 
  select(Compound.Name, percent.recovery) %>% 
   dplyr::rename(`per.rec.pH5` = percent.recovery)

setwd(datapath_pH8)
recovery_pH8 <- read.csv("RecoveryValues_postBMIS_pH8_Cyano_NOVB1.csv", row.names = 1)

recovery_pH8 <- recovery_pH8 %>% 
  select(Compound.Name, percent.recovery) %>% 
   dplyr::rename(`per.rec.pH8` = percent.recovery)

setwd(datapath_pH2)
recovery_pH2 <- read.csv("RecoveryValues_postBMIS_pH2_Cyano.csv", row.names = 1)

recovery.summary <- recovery_pH2 %>% 
  select(Compound.Name, percent.recovery, Group) %>% 
  dplyr::rename(`per.rec.pH2` = percent.recovery) %>%
  full_join(recovery_pH5, "Compound.Name") %>% 
  full_join(recovery_pH8, "Compound.Name") %>% 
  select(Compound.Name, Group, `per.rec.pH2`, `per.rec.pH5`, `per.rec.pH8`) %>% 
  filter(!Group == "Internal Std")

recovery.summary[is.na(recovery.summary)] <- 0
  
 setwd(summarypath) 
  
write_csv(recovery.summary, "RecoveryTestsSummary_Recoveries_Cyano.csv")
```
Load in Background Concentration data

```{r}
setwd(datapath_pH2)
back.conc.ph2 <- read.csv("BackgroundConcentrations_SPE_pH2_Cyano.csv")

setwd(datapath_pH5)
back.conc.ph5 <- read.csv("BackgroundConcentrations_SPE_pH5_Cyano.csv")

back.conc.ph5 <- back.conc.ph5 %>% 
  select(Compound.Name, average.adj.conc, sd.adj.conc, average.raw.conc, sd.raw.conc) %>% 
  dplyr::rename(pH5_adj.conc = average.adj.conc) %>% 
  dplyr::rename(pH5_sd = sd.adj.conc) %>% 
  dplyr::rename(pH5_raw.conc = average.raw.conc) %>% 
  dplyr::rename(pH5_sd.raw = sd.raw.conc)

setwd(datapath_pH8)
back.conc.ph8 <- read.csv("BackgroundConcentrations_SPE_pH8_Cyano.csv")

back.conc.ph8 <- back.conc.ph8 %>% 
  select(Compound.Name, average.adj.conc, sd.adj.conc, average.raw.conc, sd.raw.conc) %>% 
  dplyr::rename(pH8_adj.conc = average.adj.conc) %>% 
  dplyr::rename(pH8_sd = sd.adj.conc) %>% 
  dplyr::rename(pH8_raw.conc = average.raw.conc) %>% 
  dplyr::rename(pH8_sd.raw = sd.raw.conc)

back.conc.summary <- back.conc.ph2 %>% 
  select(Compound.Name, average.adj.conc, sd.adj.conc, average.raw.conc, sd.raw.conc) %>% 
  dplyr::rename(pH2_adj.conc = average.adj.conc) %>% 
  dplyr::rename(pH2_sd = sd.adj.conc) %>% 
  dplyr::rename(pH2_raw.conc = average.raw.conc) %>% 
  dplyr::rename(pH2_sd.raw = sd.raw.conc) %>% 
  full_join(back.conc.ph5, "Compound.Name") %>% 
  full_join(back.conc.ph8, "Compound.Name")

back.conc.summary[is.na(back.conc.summary)] <- 0

back.conc.summ.test <- round(back.conc.summary[,2:13], 2)
 back.conc.summ.test <- format(back.conc.summary, digits=1) 

setwd(summarypath)

write_csv(back.conc.summ.test, "RecoveryTestsSummary_BackgroundConc_Cyano.csv")
```

#Ranked table
```{r}
recovery.summary <- recovery.summary %>% 
  filter(!Compound.Name == "trans cinnamic acid")

unique.names <-unique(recovery.summary$Compound.Name)

recovery.summary.long <- recovery.summary %>% 
  gather(per.rec.pH2, per.rec.pH5, per.rec.pH8, key="pH", value="percent.recovery") 

Names <- colnames(recovery.summary.long)



data_ranked = data.frame(matrix(vector(), 0, length(Names) + 1,
                                        dimnames=list(c(), c(Names, "rank"))),
                                 stringsAsFactors=F)

for (i in 1:length(unique.names)) {
  
  compound_set <- as.data.frame(recovery.summary.long) %>% 
    filter(Compound.Name == unique.names[i]) %>%
    arrange(desc(percent.recovery)) %>%
    mutate(rank = c(3:1))
  
   compound_set$rank <- ifelse(compound_set$percent.recovery < 1, 0, compound_set$rank)
  
  data_ranked <- rbind(data_ranked, compound_set)
  
  #print(i)
}

recovery.summary.ranks <- data_ranked %>% 
  select(-percent.recovery, -Group) %>% 
  spread(key= Compound.Name, value= rank)

recovery.summary.ranks <- recovery.summary.ranks %>% 
  mutate(rank.total = rowSums(recovery.summary.ranks[,2:ncol(recovery.summary.ranks)])) %>%
  select(pH, rank.total, everything()) %>%
  arrange(desc(rank.total))

recovery.ranks.simple <- recovery.summary.ranks %>% select(pH, rank.total)
write_csv(recovery.ranks.simple, "~/Desktop/MetabolomicsProjects/SPEvsEtOAcTest/RecoveryTests/Cyano_RecoveryRanks_allcompounds.csv")

```

#Ranked Table, at least 10% Recovery
```{r}
recovery.summary <- recovery.summary %>% 
  filter(!Compound.Name == "trans cinnamic acid")

unique.names <-unique(recovery.summary$Compound.Name)

recovery.summary.long <- recovery.summary %>% 
  gather(per.rec.pH2, per.rec.pH5, per.rec.pH8, key="pH", value="percent.recovery") 

Names <- colnames(recovery.summary.long)



data_ranked_10min = data.frame(matrix(vector(), 0, length(Names) + 1,
                                        dimnames=list(c(), c(Names, "rank"))),
                                 stringsAsFactors=F)

for (i in 1:length(unique.names)) {
  
  compound_set <- as.data.frame(recovery.summary.long) %>% 
    filter(Compound.Name == unique.names[i]) %>%
    arrange(desc(percent.recovery)) %>%
    mutate(rank = c(3:1))
  
   compound_set$rank <- ifelse(compound_set$percent.recovery < 10, 0, compound_set$rank)
  
  data_ranked_10min <- rbind(data_ranked_10min, compound_set)
  
  #print(i)
}

recovery.summary.ranks.10min <- data_ranked_10min %>% 
  select(-percent.recovery, -Group) %>% 
  spread(key= Compound.Name, value= rank)

recovery.summary.ranks.10min <- recovery.summary.ranks.10min %>% 
  mutate(rank.total = rowSums(recovery.summary.ranks.10min[,2:ncol(recovery.summary.ranks.10min)])) %>%
  select(pH, rank.total, everything()) %>%
  arrange(desc(rank.total))

recovery.ranks.simple.10min <- recovery.summary.ranks.10min %>% select(pH, rank.total)
write_csv(recovery.ranks.simple.10min, "~/Desktop/MetabolomicsProjects/SPEvsEtOAcTest/RecoveryTests/Cyano_RecoveryRanks_10percentmin.csv")

```
